; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; default_envs = TT1ST, TT2ST, TT1DC, TT2DC, DR2ST, DR3ST, DR4ST, DR2DC, DR3DC, DR4DC

[common]
version = '"_ASIA_GPS__TEST"'

[env]
platform = intel_mcs51
board = stc15f2k60s2
upload_speed = 57600
monitor_speed = 38400
extra_scripts = pre:extra_script.py




[env:TEST]
build_flags = 
	-DVERSION=${common.version}
