__code unsigned char huongdan[]= "DH,ON dong ho chay - DH,OFF dong ho dung\n"
                                 "DH,+mm kim phut lech duong mm phut - DH,-mm lech am mm phut\n" 
                                 "DH,kkkk,tttt chinh gio kim gio thuc gio tu dong thay tttt bang auto\n"
                                 "BC,ON bao cao dau gio - BC,OFF tat bao cao dau gio\n"
                                 "BC gui bao cao - BC,DEN BC,MP3 bao cao den bao cao mp3\n"
                                 "RS reset:RS,sys reset he thong - RS,sim reset gps module\n"
                                 "RS,G,nn,gg moi nn ngay vao gio gg:06 bo dieu khien reset\n"
                                 "DEN,XOA xoa toan bo thong so den tat den\n"
                                 "DEN,tttt,mmmm x: so cap gio tat/mo tttt,mmmm gio tat/mo den\n"
                                 "MP3,X,all xoa tat ca - Mp3,X,aa,bb,cc,... xoa cac gio aa,bb,cc\n"
                                 "MP3,T,ggpp,22,11,... lap lai toi da 12 lan ggpp:gio phut phat nhac\n"
                                 "22,11 thu tu bai hat lan luot trong thu muc 2 va 1\n"
                                 "DT,0xxxxxxxxx DT,+84xxxxxxxxx thay doi so dien thoai phu\n"
                                 "DT,XOA xoa so dien thoai phu\n"
                                 "DT,ON DT,OFF - bat tat dien thoai phu\n";