__code unsigned char huongdan[]= "DH,ON dong ho chay - DH,OFF dong ho dung\n"
                                 "DH,+mm kim phut lech duong mm phut - DH,-mm lech am mm phut\n" 
                                 "DH,kkkk,kkkk,kkkk,kkkk,tttt chinh gio kim gio thuc gio tu dong thay tttt bang auto\n"
                                 "DH,xTD x la so may, T: D cho DC, S cho ST; D: A cho Atmel driver, S cho STC15 truc tiep\n"
                                 "BC,ON bao cao dau gio - BC,OFF tat bao cao dau gio\n"
                                 "BC gui bao cao - BC,DEN BC,MP3 bao cao den bao cao mp3\n"
                                 "RS reset:RS,sys reset he thong - RS,sim reset gps module\n"
                                 "RS,NG,nn,gg moi nn ngay vao gio gg:06 bo dieu khien reset\n"
                                 "DEN,XOA xoa toan bo thong so den tat den\n"
                                 "DEN,tttt,mmmm,tttt,mmmm,tttt,mmmm tttt,mmmm gio tat/mo den\n"
                                 "MP3,hhmm test bai hat luc hh gio mm phut\n"
                                 "DT,0xxxxxxxxx DT,+84xxxxxxxxx thay doi so dien thoai phu\n"
                                 "DT,XOA xoa so dien thoai phu\n"
                                 "DT,ON DT,OFF - bat tat dien thoai phu\n"
                                 "DT,GOI goi lai cho so dt chinh\n";